POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstName": "Lovestrant",
    "lastName": "Kemboi",
    "phoneNumber": "0791638771",
    "password": "1323",   
    "securityKey": "1323"
}